# Generated by Django 5.0.7 on 2024-10-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitsmodel",
            name="path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visitsmodel",
            name="timing",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
