# Generated by Django 5.0.7 on 2024-10-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0002_alter_visitsmodel_path_alter_visitsmodel_timing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitsmodel",
            name="timing",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
